#!/usr/bin/env python3
"""
Hong Kong Weather Data - Generated by OpenClaw
Retrieved: 2026-03-11 03:07:39
"""

import json

WEATHER_DATA = {
  "generalSituation": "The northeast monsoon is affecting the coast of Guangdong. Meanwhile, a band of clouds is covering the region and the northern part of South China Sea.",
  "tcInfo": "At 2 a.m., the tropical depression over the western North Pacific to the east of the Philippines was centred about 300 kilometres north of Yap. It is forecast to be slow-moving, lingering over the region.",
  "fireDangerWarning": "",
  "forecastPeriod": "Weather forecast for today",
  "forecastDesc": "Mainly cloudy at first. Cool in the morning. The minimum temperature will be about 17 degrees in the urban areas, and a couple of degrees lower in the New Territories. Becoming fine and dry during the day. The maximum temperature will be around 21 degrees. Moderate east to northeasterly winds.",
  "outlook": "Fine with relatively large temperature difference between day and night on Thursday. Windy on Friday to early Saturday.",
  "updateTime": "2026-03-11T02:45:00+08:00"
}

def print_weather_summary():
    """Print a summary of the weather data."""
    print("🌤️  Hong Kong Weather Summary")
    print("=" * 40)
    
    if WEATHER_DATA.get('mock_data'):
        weather = WEATHER_DATA.get('weather', {})
        print(f"📍 Location: {WEATHER_DATA.get('location', 'Hong Kong')}")
        print(f"🌡️  Temperature: {weather.get('temperature', 'N/A')}°C")
        print(f"💧 Humidity: {weather.get('humidity', 'N/A')}%")
        print(f"🌤️  Conditions: {weather.get('weather', 'N/A')}")
        print(f"📝 Forecast: {weather.get('forecast', 'N/A')}")
        print(f"⏰ Updated: {weather.get('update_time', 'N/A')}")
        print("\n⚠️  Note: This is mock data (real API was unavailable)")
    else:
        print("📊 Weather data retrieved from Hong Kong Observatory")
        print(f"📁 Data keys: {', '.join(WEATHER_DATA.keys())}")
        print("\n🔗 For detailed forecast, visit: https://www.hko.gov.hk")
    
    print("=" * 40)

if __name__ == "__main__":
    print_weather_summary()
